### PR TITLE
Set username as triggerValue when possible

### PR DESCRIPTION
**Pull request by BadWolf42**
## Proposed change

As per feature request here: https://community.jeedom.com/t/utilisateur-ayant-execute-la-commande/4488

Last user who executed the scenario is available using `triggerValue()` when `trigger()` is 'user'.

(Also fixed a typo in core/ajax/user.ajax.php)

## Type of change
- [x] Core new feature
- [x] Code quality improvements

## Test check
image

## Documentation
N/A

### CODE REVIEW

**Comment by rocket13011** [comment]
@CodiumAI-Agent /review

**Review by zoic21 — APPROVED** [review]

**Comment by BadWolf42** [comment]
Hello @Hotfirenet & @Sekiro-kost,
Any news regarding this PR, what should I change to have it merged?
Regards,
Bad

**Comment by zoic21** [comment]
Hello,

No problem with this PR just we wait core 4.5 (maybe this week or next week).

**Comment by zoic21** [comment]
Hello,
It's time to merge !!!!! Can you review your PR to adapt of new code of scenario, specially using tag to pass username

**Comment by zoic21** [comment]
Hello,

I think we can do better for this PR, currently it's use cache but now it's better to you use tag like this : 
https://github.com/jeedom/core/blob/alpha/core/class/scenario.class.php#L378

Now tag is instanciated for current launch and do not impact other scenario launch

**Comment by BadWolf42** [comment]
Using the tag system in the instance, it is way easier to get the user who triggered the scenario.
This could also be done to identify which API key triggered the scenario in jeeApi and proApi.

**Pull request merged**
