### PR TITLE
Core/TLS checks: remove last occurences of --no-check-certificate

### PR DESCRIPTION
**Pull request by rpi-jeedom**
Follow up of https://github.com/jeedom/core/pull/1577.

### CODE REVIEW

**Comment by zoic21** [comment]
Hello
For URL it's needed lot of client use is own url reposotiry un https without sign certificate so we must remove check.

**Comment by rpi-jeedom** [comment]
Alright I see... Thanks for the clarification.

I am not really knowledgeable with that part of the code, but it seems this is the same codepath to retrieve official updates from Jeedom, is it correct? In that case we should maybe do something like:

`
if ($url != "jeedom.com")
  $cmd .= " --no-check-certificate";
`

That would cover the main case.

**Comment by zoic21** [comment]
No it's not the same it's use only by few client, 
otherwise I would of course correct it too

**Comment by rpi-jeedom** [comment]
Understood! Sorry for bothering you. :)

**Pull request closed without merging**
