### PR TITLE
docker: use jeedom password variable name

### PR DESCRIPTION
**Pull request by edgd1er**
Fix the database password for docker env.

## Description

My last PR introduced a variable name change that does not belong to this project. As a result, the database password configuration may be wrongly set.
This PR restore the previous name.

### Related issues/external references

Fixes #

## Types of changes

- [x] Bug fix _(non-breaking change which fixes)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [ ] Documentation improvement

## PR checklist

- x ] I have checked there is no other PR open for the same change.
- [x] I have read the [[La ligne directrice pour contribuer à ce projet / Contribution guidelines for this project](.github/CONTRIBUTING.md)).
- [x] I grant the project the right to include and distribute the code under the GNU.
- [ ] I have added tests to cover my changes.
- [x] I have verified that the code complies with the projects coding standards.
- [ ] [Required for new sniffs] I have added MD documentation for the sniff.

### CODE REVIEW

**Comment by zoic21** [comment]
Can you describe more ? What is the purpose ?

**Comment by edgd1er** [comment]
The variable replaced is the one used in my image, jeedom has different names for DB vars.
the proper name is DB_PASSWORD, not MYSQL_JEEDOM_PASSWORD

current init.sh
https://github.com/jeedom/core/blob/5de9f9cd3324271c5939875d47fa3fcdbe34ceb2/install/OS_specific/Docker/init.sh#L99

**Comment by zoic21** [comment]
I don't understand tou replace MARIADB_JEEDOM_PASSWD by DB_PASSWORD and you say you replace with MYSQL_JEEDOM_PASSWD in common.config.php . I'am little lost

**Comment by edgd1er** [comment]
> I don't understand tou replace MARIADB_JEEDOM_PASSWD by DB_PASSWORD and you say you replace with MYSQL_JEEDOM_PASSWD in common.config.php . I'am little lost

you are right, I mixed up words and projects.
Line 314 and following use MARIADB_JEEDOM_PASSWD to setup common.config.php.
This var MARIADB_JEEDOM_PASSWD does not belong to this project and is never set. the name value for this project is DB_PASSWORD.

for the record, MYSQL_JEEDOM_PASSWD is the variable name for the jeedom's docker image I've been running for 7 years . I changed few days ago my var names to match jeedom/core's and avoid situation where my PR would push the wrong variables when I backport evolution from my project to yours. As you can see, I was not as successful as I thought.

Please note that a the moment, anyone trying to setup a jeedom would have to fix manually the file common.config.php as DB_PASSWORD would be replaced with en empty value.
Docker users would have their jeedom conf ok as this file is written at each boot.

**Comment by pifou25** [comment]
Hello @edgd1er 
I think we don't care about the variable name, as it is never setted anywhere, as far as I can see... (?) 
I used it in my docker-compose.yml and I still use the old name (MYSQL_JEEDOM_PASSWD)... no need to fix it once it is running :) 
And there is no `docker-compose.yml` anymore in this repo.
The variable is setted at the begining of the script with a random default value
https://github.com/jeedom/core/blob/3fbddab2b956ed3a63e5889b1f917d4fa7bc4388/install/install.sh#L417

Anyway, it is a good idea to revert to the old name and stop changing it pls 👍

**Comment by edgd1er** [comment]
As you wish, i'll close the PR.
Thanks you for helping jeedom to have a better docker image. There is a lot to do.

**Pull request closed without merging**
