### PR TITLE
Add more readability to inputbox on scenario

### PR DESCRIPTION
**Pull request by DuchkPy**
Very often the full name of the equipment does not fit in the input field.
So having `Name` and `Value` input on 2 lines helps with readability.

### CODE REVIEW

**Comment by KiboOst** [comment]
Not fond of making scenario taking even more spaces on screen ...

**Comment by DuchkPy** [comment]
You are right, it take more vertical space.

But if we compare both following images (on a 1920px wide screen), only the second one allow to be able to correctly read what is written on `Value` field :
1. Current display :
image
2. proposed display :
image

Also, sometime it's even longer leading to be very difficult to read.

**Comment by KiboOst** [comment]
It adds double the space each time you edit the scenario for every action, to something that will be used once upon a time ...

Something like this may be a lot better :

scInputEdit

**Comment by DuchkPy** [comment]
Your proposal is a way better, congratulation.
If it's possible to have this feature I will be more than happy. As the field is even bigger and more confortable to put everything we need inside.

**Comment by DuchkPy** [comment]
@KiboOst does this feature as been implemented ?
If yes, how to access to it ?

**Comment by KiboOst** [comment]
Yes this is in alpha for some time now, just ctrl+click in the field

**Pull request closed without merging**
