### PR TITLE
Optimize replacement of '=' by '==' in function evaluate()

### PR DESCRIPTION
**Pull request by BadWolf42**
Replace all '=' by '==' in 1 pass instead of 7
Avoid messing with '==' '===' '>=' '<=' '!=' '!==' as expected

### CODE REVIEW

**Comment by KiboOst** [comment]
Wait 4.3 to test ;-)

**Comment by KiboOst** [comment]
Done some test, doesn't seems to do same thing:

$a = $b : $a == $b : OK
$a >== $b  : $a >== $b : NOK
$a !== $b : $a !== $b : NOK

**Comment by BadWolf42** [comment]
Hello @KiboOst, merci pour ton retour.

En effet, l'ancien fonctionnement n'est pas respecté pour les opérateurs `>==` et `!==`.
Pour ma défense :
`>==` n'existe pas, donc lèvera un erreur
`!==` est lui légitime et ne devrait pas être modifié (comme `===`)

Souhaties-tu que je reproduise exactement le fonctionnement actuel ?

**Comment by KiboOst** [comment]
I guess it should do the same thing, specially on such critical function part.
For example, >== should not raise an error, but be corrected to function like >=

@zoic21 could you confirm such assertion ?

**Comment by BadWolf42** [comment]
Hi,
This regexp has the same behavior then current code:
`$expr = preg_replace("/(?|([<>!])=(?:=|===)|([^<>!]==)={1,2}|([^<>!]=)=?)/", "$1=", $string);`
 on the following test set:
`"=", "==", "===", "====", "!=", "!==", "!===", "<=", "<==", "<=>", "<==>", ">=", ">=="`

But it's less readable and understandable then previous one, 
also it's not just a simple replacement of affectation operation `=` by test operation `==`.

**Pull request merged**
