### PR TITLE
Update cmd.action.slider.button.html

### PR DESCRIPTION
**Pull request by tibo888**
Ajout d'une variable globale dynamique  permettant d'afficher un loader selon le paramètre optionnel

### CODE REVIEW

**Comment by KiboOst** [comment]
Sorry but I don't get it, this global parameter isn't used later in ajax call or cmd class. Would you elaborate on the goal of this and a use case ?

**Comment by tibo888** [comment]
Hello, you are righ, you cannot use it from ajax or php class. 
The goal : i used an action slider (curseur) from a virtual. I used the widget "Button" for change the design. When i click on the widget the result is very long, so i used a "Optional widget parameters" ->Name = "global", Value = "true". When i click on the wigdet the loader is visible

**Comment by tibo888** [comment]
I think this will be a good idea, add global: $ .issetWidgetOptParam ('# global #', 'global') on all templates

**Comment by KiboOst** [comment]
After some test I don't see such behavior. being button or default is just the same.
And I don't get how to add a param that is never used in any function would change this ?

**Comment by KiboOst** [comment]
This what I tested yes ...  ^^

**Pull request closed without merging**
