### PR TITLE
typeHinting

### PR DESCRIPTION
**Pull request by ColonelMoutarde**
## Type of change

- [x] Code quality improvements

## Documentation

[beta-testing](https://doc.jeedom.com/en_US/beta/)
[contribute](https://doc.jeedom.com/en_US/contribute/)
[community](https://community.jeedom.com/)
[plugins](https://doc.jeedom.com/en_US/dev/)

### CODE REVIEW

**Comment by KiboOst** [comment]
Not an expert for this, but
https://www.php.net/manual/en/language.types.declarations.php
8.1.0 | Returning by reference from a void function is now deprecated.

**Comment by Mips2648** [comment]
I think backward support is an issue with the type of declaration because this will be enforced during runtime

an other way to cover the need of typehinting  is to add comment before functions like:
```PHP
/**
 * @return bool
 */
 function myFunctionReturnBool() {}
```

recent editors will be able to cope with that raising warnings if an issue is detected but no risk of impact, I think it is preferable to only use this as a first step
on top this allow better generation of phpDoc ;)

**Comment by ColonelMoutarde** [comment]
hi, if i see the minimum declaration version of PHP in composer.json it's php7.Mmy code is php7 compliant

**Comment by KiboOst** [comment]
I'm all for this, but I think it's a bit late for 4.4.
4.4 is near feature fixed and ready for beta step, and adding such thing could break any call to any function, which would need heavy testing.

**Comment by ColonelMoutarde** [comment]
up

**Pull request merged**
