### PR TITLE
clarify health page

### PR DESCRIPTION
**Pull request by Mips2648**
## Proposed change
clarify health page, lot of users think it is the Apache version number

## Type of change
- [X] UI improvement

- [ ] 3rd party lib update
- [ ] Bugfix (non breaking change)
- [ ] Core new feature
- [ ] UI new functionnality
- [ ] Code quality improvements
- [ ] Core documentation

## Test check
I test that the label is not to long to display

## Documentation

[beta-testing](https://doc.jeedom.com/en_US/beta/)
[contribute](https://doc.jeedom.com/en_US/contribute/)
[community](https://community.jeedom.com/)
[plugins](https://doc.jeedom.com/en_US/dev/)

### CODE REVIEW

**Review by zoic21 — APPROVED** [review]

**Comment by Salvialf** [comment]
Thanks @Mips2648,

Maybe it's better to write "Nombre de processus" in full fr don't you think ?

**Comment by Mips2648** [comment]
Indeed, I agree

**Comment by Mips2648** [comment]
change done

**Comment by Mips2648** [comment]
@zoic21 et @Salvialf vous penserez à approuver à nouveau le change? le review a sauté avec le changement de texte :-)
merci

**Review by Salvialf — APPROVED** [review]

**Review by Sekiro-kost — APPROVED** [review]

**Pull request merged**
